"""
Layer 2: Metadata Service
C2PA 및 EXIF 메타데이터 분석
"""

import io
import json
from typing import Dict, Any, List, Optional
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

# C2PA는 선택적 import (설치 안 되어 있을 수 있음)
try:
    from c2pa import Reader
    C2PA_AVAILABLE = True
except ImportError:
    C2PA_AVAILABLE = False


class MetadataService:
    """이미지 메타데이터 분석 서비스"""
    
    # AI 도구 시그니처 패턴
    AI_TOOL_SIGNATURES = [
        # 소프트웨어 이름
        "midjourney",
        "dall-e",
        "dall·e",
        "stable diffusion",
        "stability.ai",
        "novelai",
        "leonardo.ai",
        "runway",
        "firefly",
        "adobe firefly",
        "imagen",
        "dreamstudio",
        "nightcafe",
        "artbreeder",
        "craiyon",
        "bluewillow",
        "playground ai",
        "ideogram",
        "flux",
        
        # 일반적인 AI 관련 키워드
        "ai generated",
        "ai-generated",
        "generated by ai",
        "artificial intelligence",
        "machine learning generated",
        "synthetic image",
        "diffusion model",
    ]
    
    def analyze(self, image_bytes: bytes, filename: str) -> Dict[str, Any]:
        """
        이미지 메타데이터 종합 분석
        """
        result = {
            "has_c2pa": False,
            "c2pa_info": None,
            "exif_data": None,
            "ai_tool_signatures": [],
            "software_used": None,
            "creation_date": None,
            "image_info": None
        }
        
        # 1. EXIF 분석
        exif_result = self._extract_exif(image_bytes)
        result["exif_data"] = exif_result.get("exif")
        result["software_used"] = exif_result.get("software")
        result["creation_date"] = exif_result.get("creation_date")
        result["image_info"] = exif_result.get("image_info")
        
        # 2. C2PA 분석
        if C2PA_AVAILABLE:
            c2pa_result = self._analyze_c2pa(image_bytes, filename)
            result["has_c2pa"] = c2pa_result.get("has_c2pa", False)
            result["c2pa_info"] = c2pa_result.get("info")
        
        # 3. AI 도구 시그니처 검사
        result["ai_tool_signatures"] = self._detect_ai_signatures(result)
        
        return result
    
    def _extract_exif(self, image_bytes: bytes) -> Dict[str, Any]:
        """EXIF 메타데이터 추출"""
        result = {
            "exif": {},
            "software": None,
            "creation_date": None,
            "image_info": {}
        }
        
        try:
            img = Image.open(io.BytesIO(image_bytes))
            
            # 기본 이미지 정보
            result["image_info"] = {
                "format": img.format,
                "mode": img.mode,
                "size": {"width": img.width, "height": img.height}
            }
            
            # EXIF 데이터 추출
            exif_data = img._getexif()
            if exif_data:
                for tag_id, value in exif_data.items():
                    tag = TAGS.get(tag_id, tag_id)
                    
                    # 바이너리 데이터 제외
                    if isinstance(value, bytes):
                        continue
                    
                    # 특별 처리
                    if tag == "Software":
                        result["software"] = str(value)
                    elif tag in ["DateTime", "DateTimeOriginal", "DateTimeDigitized"]:
                        result["creation_date"] = str(value)
                    
                    result["exif"][tag] = str(value) if not isinstance(value, (int, float)) else value
            
            # PNG tEXt 청크 등 추가 메타데이터
            if hasattr(img, 'info') and img.info:
                for key, value in img.info.items():
                    if isinstance(value, str) and key not in result["exif"]:
                        result["exif"][f"PNG_{key}"] = value
                        
                        # parameters 필드 (Stable Diffusion 등)
                        if key.lower() == "parameters":
                            result["exif"]["sd_parameters"] = value
                            
        except Exception as e:
            result["error"] = str(e)
        
        return result
    
    def _analyze_c2pa(self, image_bytes: bytes, filename: str) -> Dict[str, Any]:
        """C2PA Content Credentials 분석"""
        result = {
            "has_c2pa": False,
            "info": None
        }
        
        if not C2PA_AVAILABLE:
            result["error"] = "c2pa-python not installed"
            return result
        
        try:
            # C2PA manifest 읽기 시도
            reader = Reader.from_stream("image/jpeg", io.BytesIO(image_bytes))
            
            if reader:
                result["has_c2pa"] = True
                
                # manifest 정보 추출
                manifest_json = reader.json()
                manifest_data = json.loads(manifest_json)
                
                result["info"] = {
                    "active_manifest": manifest_data.get("active_manifest"),
                    "manifests": list(manifest_data.get("manifests", {}).keys()),
                }
                
                # AI 생성 관련 assertion 확인
                for manifest_id, manifest in manifest_data.get("manifests", {}).items():
                    assertions = manifest.get("assertions", [])
                    for assertion in assertions:
                        label = assertion.get("label", "")
                        if "ai" in label.lower() or "generative" in label.lower():
                            result["info"]["ai_related_assertions"] = result["info"].get("ai_related_assertions", [])
                            result["info"]["ai_related_assertions"].append(assertion)
                            
        except Exception as e:
            # C2PA가 없는 이미지는 정상적으로 예외 발생
            result["error"] = str(e) if "no manifest" not in str(e).lower() else None
        
        return result
    
    def _detect_ai_signatures(self, metadata_result: Dict[str, Any]) -> List[str]:
        """메타데이터에서 AI 도구 시그니처 탐지"""
        detected = []
        
        # 검사할 텍스트 필드들
        text_to_check = []
        
        if metadata_result.get("software_used"):
            text_to_check.append(metadata_result["software_used"])
        
        if metadata_result.get("exif_data"):
            for key, value in metadata_result["exif_data"].items():
                if isinstance(value, str):
                    text_to_check.append(value)
        
        if metadata_result.get("c2pa_info"):
            text_to_check.append(json.dumps(metadata_result["c2pa_info"]))
        
        # 시그니처 매칭
        combined_text = " ".join(text_to_check).lower()
        
        for signature in self.AI_TOOL_SIGNATURES:
            if signature.lower() in combined_text:
                detected.append(signature)
        
        return list(set(detected))  # 중복 제거
    
    def has_ai_indicators(self, metadata_result: Dict[str, Any]) -> bool:
        """AI 생성 지표가 있는지 확인"""
        # C2PA에 AI 관련 정보가 있는 경우
        if metadata_result.get("has_c2pa"):
            c2pa_info = metadata_result.get("c2pa_info", {})
            if c2pa_info.get("ai_related_assertions"):
                return True
        
        # AI 도구 시그니처가 발견된 경우
        if metadata_result.get("ai_tool_signatures"):
            return True
        
        # EXIF에 AI 관련 정보가 있는 경우
        exif = metadata_result.get("exif_data", {})
        if exif.get("sd_parameters"):  # Stable Diffusion
            return True
        
        return False
